import { Breakdown } from "@/comps/Breakdown";
import { Button } from "@/comps/Button";
import { Call } from "@/comps/Call";
import { Footer } from "@/comps/Footer";
import { Header } from "@/comps/Header";
import { RecentWork, RecentWorkList } from "@/comps/RecentWorkList";
import { Testimonial, TestimonialList } from "@/comps/TestimonialList";
import styles from "@/styles/home.module.scss";
import Head from 'next/head'

import Image from "next/image";


export default function Home() {
  return (
    <>
      <Head>
        <title>Void Studios - Home</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <Header />

        {/* Hero */}
        <div className={styles.hero}>
          <div className={styles.hero_img} />
          {/* <video autoPlay muted loop className={styles.video}>
            <source src="/videos/hero.mp4" type="video/mp4" />
          </video> */}
          <div className={styles.overlay} />
          <div className={styles.hero_text}>
            <h1>
              Leading Web Development.<br />
              Mobile App Development.<br />
              IoT Prototyping.<br />
              Filling the void.<br />
            </h1>
            <Button onClick={() => { }}>
              Start your journey today!
            </Button>
          </div>
        </div>

        {/* Mission statement */}
        <div className={styles.mission}>
          <h2>
            Here at Void Studios our mission is to make people’s living more convenient and efficient by creating cutting edge technology enabling the future.
            <br />
            <br />
            We are here to fill the void.
          </h2>
        </div>

        {/* Recent Work */}
        <RecentWorkList recent_work={case_studies} />

        {/* Our Focus */}
        <div className={styles.focus_con}>
          <h3>Our Focus</h3>
          <div className={styles.focus_items}>
            <div className={styles.focus_item_con}>
              <Image src="/icons/mobile.png" alt="Web Icon" width={140} height={250} />
              <h4>Mobile & Web Apps</h4>
              <p>Whether you need an Android, iOS, or cross platform mobile app we have you covered. We can seamlessly integrate your business and bring it into the future with a realiable and trustworthy mobile app.</p>
              <div className={styles.a_wrapper}>
                <a href={`services#$app-dev`}>See more</a>
              </div>
            </div>

            <div className={styles.focus_item_con}>
              <Image src="/icons/laptop.png" alt="Web Icon" width={140} height={250} />
              <h4>Performant Websites</h4>
              <p>Whether you need an Android, iOS, or cross platform mobile app we have you covered. We can seamlessly integrate your business and bring it into the future with a realiable and trustworthy mobile app.</p>
              <div className={styles.a_wrapper}>
                <a href={`services#$websites`}>See more</a>
              </div>
            </div>

            <div className={styles.focus_item_con}>
              <Image src="/icons/iot.png" alt="Web Icon" width={140} height={250} />
              <h4>IoT Prototyping</h4>
              <p>Whether you need an Android, iOS, or cross platform mobile app we have you covered. We can seamlessly integrate your business and bring it into the future with a realiable and trustworthy mobile app.</p>
              <div className={styles.a_wrapper}>
                <a href={`services#$iot`}>See more</a>
              </div>
            </div>
          </div>
        </div>

        {/* CTA */}
        <div className={styles.cta}>
          <h2>
            Got an idea for an app?
            <br />
            Want to revolutionize your business?
            <br />
            Call Void Studios today!
          </h2>
          <div className={styles.button_wrapper}>
            <Button onClick={() => { }}>Book a call today!</Button>
          </div>
        </div>

        {/* Our Process */}
        <div className={styles.process}>
          <h3>Our Process</h3>

          <Breakdown title="Discovery" number={1}>
            <p>
              In the first phase of our journey together, we dive deep into innovative ideas. Whether you're envisioning an Android, iOS, or cross-platform mobile app, our team is your think-tank. We explore, ideate, and sculpt your vision into reality.
              <br />
              <br />
              Our brainstorming sessions are dynamic and collaborative. We dissect your business, its unique needs, and its future goals. We identify opportunities and challenges, seeking inspiration from the digital landscape and IoT possibilities.
              <br />
              <br />
              With our software development expertise in React, NEXTJS, ExpressJS, and more, we don't just create apps; we craft solutions that set you apart. Our brainstorming process ensures that your project is not just another app but a transformational leap into the digital era.
              <br />
              <br />
              Join us in this creative journey, where your ideas blend seamlessly with our technical prowess, bringing your vision to life in a reliable and innovative way. Together, we'll redefine your digital future."
              <br />
              <br />
            </p>
          </Breakdown>
          <Breakdown title="Research" number={2}>
            <p>
              In the first phase of our journey together, we dive deep into innovative ideas. Whether you're envisioning an Android, iOS, or cross-platform mobile app, our team is your think-tank. We explore, ideate, and sculpt your vision into reality.
              <br />
              <br />
              Our brainstorming sessions are dynamic and collaborative. We dissect your business, its unique needs, and its future goals. We identify opportunities and challenges, seeking inspiration from the digital landscape and IoT possibilities.
              <br />
              <br />
              With our software development expertise in React, NEXTJS, ExpressJS, and more, we don't just create apps; we craft solutions that set you apart. Our brainstorming process ensures that your project is not just another app but a transformational leap into the digital era.
              <br />
              <br />
              Join us in this creative journey, where your ideas blend seamlessly with our technical prowess, bringing your vision to life in a reliable and innovative way. Together, we'll redefine your digital future."
              <br />
              <br />
            </p>
          </Breakdown>
          <Breakdown title="Design" number={3}>
            <p>
              In the first phase of our journey together, we dive deep into innovative ideas. Whether you're envisioning an Android, iOS, or cross-platform mobile app, our team is your think-tank. We explore, ideate, and sculpt your vision into reality.
              <br />
              <br />
              Our brainstorming sessions are dynamic and collaborative. We dissect your business, its unique needs, and its future goals. We identify opportunities and challenges, seeking inspiration from the digital landscape and IoT possibilities.
              <br />
              <br />
              With our software development expertise in React, NEXTJS, ExpressJS, and more, we don't just create apps; we craft solutions that set you apart. Our brainstorming process ensures that your project is not just another app but a transformational leap into the digital era.
              <br />
              <br />
              Join us in this creative journey, where your ideas blend seamlessly with our technical prowess, bringing your vision to life in a reliable and innovative way. Together, we'll redefine your digital future."
              <br />
              <br />
            </p>
          </Breakdown>
          <Breakdown title="Develop" number={4}>
            <p>
              In the first phase of our journey together, we dive deep into innovative ideas. Whether you're envisioning an Android, iOS, or cross-platform mobile app, our team is your think-tank. We explore, ideate, and sculpt your vision into reality.
              <br />
              <br />
              Our brainstorming sessions are dynamic and collaborative. We dissect your business, its unique needs, and its future goals. We identify opportunities and challenges, seeking inspiration from the digital landscape and IoT possibilities.
              <br />
              <br />
              With our software development expertise in React, NEXTJS, ExpressJS, and more, we don't just create apps; we craft solutions that set you apart. Our brainstorming process ensures that your project is not just another app but a transformational leap into the digital era.
              <br />
              <br />
              Join us in this creative journey, where your ideas blend seamlessly with our technical prowess, bringing your vision to life in a reliable and innovative way. Together, we'll redefine your digital future."
              <br />
              <br />
            </p>
          </Breakdown>
          <Breakdown title="Iterate" number={5}>
            <p>
              In the first phase of our journey together, we dive deep into innovative ideas. Whether you're envisioning an Android, iOS, or cross-platform mobile app, our team is your think-tank. We explore, ideate, and sculpt your vision into reality.
              <br />
              <br />
              Our brainstorming sessions are dynamic and collaborative. We dissect your business, its unique needs, and its future goals. We identify opportunities and challenges, seeking inspiration from the digital landscape and IoT possibilities.
              <br />
              <br />
              With our software development expertise in React, NEXTJS, ExpressJS, and more, we don't just create apps; we craft solutions that set you apart. Our brainstorming process ensures that your project is not just another app but a transformational leap into the digital era.
              <br />
              <br />
              Join us in this creative journey, where your ideas blend seamlessly with our technical prowess, bringing your vision to life in a reliable and innovative way. Together, we'll redefine your digital future."
              <br />
              <br />
            </p>
          </Breakdown>
        </div>

        {/* Testimonials */}
        <div className={styles.testimonials}>
          <h3>What our clients have to say.</h3>
          <TestimonialList testimonials={testimonials} />
        </div>

        {/* Cal.com - Book a call */}
        <Call />

        <Footer />
      </main >
    </>
  )
}


// Define some case studies
export const case_studies: RecentWork[] = [
  {
    id: 1,
    title: "Bulb Prototype | Environment Soil Measurement IoT Device",
    desc: "The Bulb prototype is used for measuring soil moisture condictions, it includes a pairing app that allows users to take measurements.",
    tags: ["Agriculture", "IoT Prototype", "Mobile App Development", "Web App Development"],
    img: "/img/bulb.png"
  },
  {
    id: 2,
    title: "23rd Street Marketing | Dashboard Web App",
    desc: "The 23rd Street Marketing dashboard is used for managing clients, projects, and employees. It includes a custom built CMS.",
    tags: ["Marketing", "Web App Development", "CMS"],
    img: "/img/23rd-dash.png"
  }
];


// Define some testimonials
export const testimonials: Testimonial[] = [
  {
    logo: "/img/mediaonmars.png",
    name: "Kammi Rapsey",
    position: "Principle",
    comment: "We have worked with Matt for many years and find him a pleasure to work with. He has a can-do work ethic and is professional and reliable."
  },
  {
    logo: "/img/23rd.png",
    name: "Bailey Robinson",
    position: "Founder",
    comment: "Matt is a great developer and has been a pleasure to work with. He has a great work ethic and is always willing to go the extra mile."
  },
  {
    logo: "/img/23rd.png",
    name: "Bailey Robinson",
    position: "Founder",
    comment: "Matt is a great developer and has been a pleasure to work with. He has a great work ethic and is always willing to go the extra mile."
  }
]
